# necessary for conformance
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv6
  disableDefaultCNI: true
nodes:
# the control plane node
- role: control-plane
- role: worker
- role: worker
